---
# tasks file for roles/BDD

- name: Pull the BDD image
  docker_image:
    name: hmtgn/tp1-database
    tag: latest
    source: pull
  vars:
      ansible_python_interpreter: /usr/bin/python3

- name: Run BDD
  docker_container:
    state: started
    name: mypostgresqlfinal
    image: hmtgn/tp1-database
    networks: 
      - name: "app-network"
  vars:
      ansible_python_interpreter: /usr/bin/python3