version: '3.7'

services:
  backend:
    container_name: backend
    build: .\backend\simple-api-student-main
    environment:
      DB_host: database
      DB_port: 5432
      DB_name: db
      
    networks:
      - app-network
    depends_on:
      - database

  database:
    container_name: database
    build: .\DB\
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app-network

  httpd:
    container_name: httpd
    build: ./frontend
    environment:
      BACKEND_host: backend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:


volumes:
  postgresdata:
