---
# tasks file for roles/API
- name: Pull the API Image
  docker_image:
    name: hmtgn/tp1-backend
    tag: latest
    source: pull
  vars:
      ansible_python_interpreter: /usr/bin/python3

- name: Run API
  docker_container:
    name: backend
    image: hmtgn/tp1-backend
    networks: 
      - name: "app-network"
    state: started
  vars:
      ansible_python_interpreter: /usr/bin/python3