name: CI devops 2024

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout du code GitHub
        uses: actions/checkout@v2.5.0

      - name: Configuration de JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Construction et test avec Maven
        run: mvn clean verify
